refactor: check if tests pass or fail

diff --git a/iOS-coverage-script/test b/iOS-coverage-script/test
--- a/iOS-coverage-script/test
+++ b/iOS-coverage-script/test
@@ -1,19 +1,40 @@
 #!/bin/bash
 
-PROJECT_DIR="./francesgo-ios"
-XCODE_PROJECT="FrancesGo.xcworkspace"
+PROJECT_DIR="path/to/folder"
+XCODE_PROJECT="file.xcworkspace"
 BUILD_DIR="${PROJECT_DIR}/BuildTemp"
-SCHEME="FrancesGo"
-BINARY_PATH="${BUILD_DIR}/Products/AdHocDebugDesa-iphonesimulator/francesgo-de"
+SCHEME="yourScheme"
+BINARY_PATH="${BUILD_DIR}/Products/AdHocDebugDesa-iphonesimulator/your/folder"
 
-echo "##### Testing #####"
-xcodebuild test -workspace ${PROJECT_DIR}/${XCODE_PROJECT} -scheme ${SCHEME} -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' -derivedDataPath ${BUILD_DIR} -enableCodeCoverage YES | xcpretty -s -c
+echo "##### 🚓 Testing #####"
+xcodebuild test \
+    -workspace ${PROJECT_DIR}/${XCODE_PROJECT} \
+    -scheme ${SCHEME} \
+    -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' \
+    -derivedDataPath ${BUILD_DIR} \
+    -enableCodeCoverage YES
 
-echo "##### Generating report #####"
+if [[ $? == 0 ]]; then
+    echo "✅ Unit Tests Passed"
+else
+    echo "🔴 Unit Tests Failed"
+    echo "##### Deleting temporal files #####"
+    rm -rf ${BUILD_DIR}
+    exit $?
+fi
+
+echo "##### 📈 Generating report #####"
 TEST_DIR="${BUILD_DIR}/Logs/Test"
-xcrun xccov view --report --json ${TEST_DIR}/$(ls ${TEST_DIR} | tail -1) | python -m json.tool | sed -n '4'p | sed 's/lineCoverage/lines/' | sed 's/"/{ "/' | sed 's/,/ }/' | tee ${PROJECT_DIR}/covertura.json
+xcrun xccov view --report --json ${TEST_DIR}/$(ls ${TEST_DIR} | 
+    tail -1) | 
+    python -m json.tool | 
+    sed -n '4'p | 
+    sed 's/lineCoverage/lines/' | 
+    sed 's/"/{ "/' | 
+    sed 's/,/ }/' | 
+    tee ./covertura.json
 
 echo "##### Deleting temporal files #####"
 rm -rf ${BUILD_DIR}
 
-echo "##### Done #####"
+echo "##### 🎉🎉 Done #####"
